{"Id":98,"Message":"The view 'Create' was not found. Searched locations: /Views/EventLog/Create.cshtml, /Views/Shared/Create.cshtml","EventId":3,"LogLevel":"Error","IpAdress":"192.168.1.107","HostName":"DESKTOP-F285UFK","CreatedTime":"2018-01-20T13:16:46.554517Z"},
{"Id":99,"Message":"An unhandled exception has occurred while executing the request\nSystem.InvalidOperationException: The view 'Create' was not found. The following locations were searched:\r\n/Views/EventLog/Create.cshtml\r\n/Views/Shared/Create.cshtml\r\n   at Microsoft.AspNetCore.Mvc.ViewEngines.ViewEngineResult.EnsureSuccessful(IEnumerable`1 originalLocations)\r\n   at Microsoft.AspNetCore.Mvc.ViewResult.<ExecuteResultAsync>d__26.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeResultAsync>d__19.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResultFilterAsync>d__24.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()","EventId":0,"LogLevel":"Error","IpAdress":"192.168.1.107","HostName":"DESKTOP-F285UFK","CreatedTime":"2018-01-20T13:16:46.7770437Z"},
{"Id":100,"Message":"An unhandled exception has occurred while executing the request\nSystem.InvalidOperationException: The model item passed into the ViewDataDictionary is of type 'SampleCoreArch.Core.Common.Result`1[SampleCoreArch.Core.Logging.EventLog]', but this ViewDataDictionary instance requires a model item of type 'SampleCoreArch.Core.Logging.EventLog'.\r\n   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary.EnsureCompatible(Object value)\r\n   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary..ctor(ViewDataDictionary source, Object model, Type declaredModelType)\r\n   at lambda_method(Closure , ViewDataDictionary )\r\n   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorPagePropertyActivator.CreateViewDataDictionary(ViewContext context)\r\n   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorPagePropertyActivator.Activate(Object page, ViewContext context)\r\n   at Microsoft.AspNetCore.Mvc.Razor.RazorPageActivator.Activate(IRazorPage page, ViewContext context)\r\n   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderPageCoreAsync>d__16.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderPageAsync>d__15.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderAsync>d__14.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.<ExecuteAsync>d__22.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.<ExecuteAsync>d__21.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.Mvc.ViewResult.<ExecuteResultAsync>d__26.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeResultAsync>d__19.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResultFilterAsync>d__24.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()","EventId":0,"LogLevel":"Error","IpAdress":"192.168.1.107","HostName":"DESKTOP-F285UFK","CreatedTime":"2018-01-20T14:36:15.2890925Z"},
{"Id":101,"Message":"An unhandled exception has occurred while executing the request\nMicrosoft.AspNetCore.Mvc.Razor.Compilation.CompilationFailedException: One or more compilation failures occurred:\r\nD:\\Store\\VisualStudio\\2017\\Project\\SampleCoreArch\\SampleCoreArch.Web\\Views\\EventLog\\Edit.cshtml(13,135): error CS1061: 'Result<EventLog>' does not contain a definition for 'Id' and no extension method 'Id' accepting a first argument of type 'Result<EventLog>' could be found (are you missing a using directive or an assembly reference?)\r\nD:\\Store\\VisualStudio\\2017\\Project\\SampleCoreArch\\SampleCoreArch.Web\\Views\\EventLog\\Edit.cshtml(14,135): error CS1061: 'Result<EventLog>' does not contain a definition for 'Id' and no extension method 'Id' accepting a first argument of type 'Result<EventLog>' could be found (are you missing a using directive or an assembly reference?)\r\nD:\\Store\\VisualStudio\\2017\\Project\\SampleCoreArch\\SampleCoreArch.Web\\Views\\EventLog\\Edit.cshtml(15,147): error CS1061: 'Result<EventLog>' does not contain a definition for 'Id' and no extension method 'Id' accepting a first argument of type 'Result<EventLog>' could be found (are you missing a using directive or an assembly reference?)\r\nD:\\Store\\VisualStudio\\2017\\Project\\SampleCoreArch\\SampleCoreArch.Web\\Views\\EventLog\\Edit.cshtml(18,135): error CS1061: 'Result<EventLog>' does not contain a definition for 'Message' and no extension method 'Message' accepting a first argument of type 'Result<EventLog>' could be found (are you missing a using directive or an assembly reference?)\r\nD:\\Store\\VisualStudio\\2017\\Project\\SampleCoreArch\\SampleCoreArch.Web\\Views\\EventLog\\Edit.cshtml(19,135): error CS1061: 'Result<EventLog>' does not contain a definition for 'Message' and no extension method 'Message' accepting a first argument of type 'Result<EventLog>' could be found (are you missing a using directive or an assembly reference?)\r\nD:\\Store\\VisualStudio\\2017\\Project\\SampleCoreArch\\SampleCoreArch.Web\\Views\\EventLog\\Edit.cshtml(20,147): error CS1061: 'Result<EventLog>' does not contain a definition for 'Message' and no extension method 'Message' accepting a first argument of type 'Result<EventLog>' could be found (are you missing a using directive or an assembly reference?)\r\nD:\\Store\\VisualStudio\\2017\\Project\\SampleCoreArch\\SampleCoreArch.Web\\Views\\EventLog\\Edit.cshtml(23,135): error CS1061: 'Result<EventLog>' does not contain a definition for 'EventId' and no extension method 'EventId' accepting a first argument of type 'Result<EventLog>' could be found (are you missing a using directive or an assembly reference?)\r\nD:\\Store\\VisualStudio\\2017\\Project\\SampleCoreArch\\SampleCoreArch.Web\\Views\\EventLog\\Edit.cshtml(24,135): error CS1061: 'Result<EventLog>' does not contain a definition for 'EventId' and no extension method 'EventId' accepting a first argument of type 'Result<EventLog>' could be found (are you missing a using directive or an assembly reference?)\r\nD:\\Store\\VisualStudio\\2017\\Project\\SampleCoreArch\\SampleCoreArch.Web\\Views\\EventLog\\Edit.cshtml(25,147): error CS1061: 'Result<EventLog>' does not contain a definition for 'EventId' and no extension method 'EventId' accepting a first argument of type 'Result<EventLog>' could be found (are you missing a using directive or an assembly reference?)\r\nD:\\Store\\VisualStudio\\2017\\Project\\SampleCoreArch\\SampleCoreArch.Web\\Views\\EventLog\\Edit.cshtml(28,135): error CS1061: 'Result<EventLog>' does not contain a definition for 'LogLevel' and no extension method 'LogLevel' accepting a first argument of type 'Result<EventLog>' could be found (are you missing a using directive or an assembly reference?)\r\nD:\\Store\\VisualStudio\\2017\\Project\\SampleCoreArch\\SampleCoreArch.Web\\Views\\EventLog\\Edit.cshtml(29,135): error CS1061: 'Result<EventLog>' does not contain a definition for 'LogLevel' and no extension method 'LogLevel' accepting a first argument of type 'Result<EventLog>' could be found (are you missing a using directive or an assembly reference?)\r\nD:\\Store\\VisualStudio\\2017\\Project\\SampleCoreArch\\SampleCoreArch.Web\\Views\\EventLog\\Edit.cshtml(30,147): error CS1061: 'Result<EventLog>' does not contain a definition for 'LogLevel' and no extension method 'LogLevel' accepting a first argument of type 'Result<EventLog>' could be found (are you missing a using directive or an assembly reference?)\r\nD:\\Store\\VisualStudio\\2017\\Project\\SampleCoreArch\\SampleCoreArch.Web\\Views\\EventLog\\Edit.cshtml(33,135): error CS1061: 'Result<EventLog>' does not contain a definition for 'IpAdress' and no extension method 'IpAdress' accepting a first argument of type 'Result<EventLog>' could be found (are you missing a using directive or an assembly reference?)\r\nD:\\Store\\VisualStudio\\2017\\Project\\SampleCoreArch\\SampleCoreArch.Web\\Views\\EventLog\\Edit.cshtml(34,135): error CS1061: 'Result<EventLog>' does not contain a definition for 'IpAdress' and no extension method 'IpAdress' accepting a first argument of type 'Result<EventLog>' could be found (are you missing a using directive or an assembly reference?)\r\nD:\\Store\\VisualStudio\\2017\\Project\\SampleCoreArch\\SampleCoreArch.Web\\Views\\EventLog\\Edit.cshtml(35,147): error CS1061: 'Result<EventLog>' does not contain a definition for 'IpAdress' and no extension method 'IpAdress' accepting a first argument of type 'Result<EventLog>' could be found (are you missing a using directive or an assembly reference?)\r\nD:\\Store\\VisualStudio\\2017\\Project\\SampleCoreArch\\SampleCoreArch.Web\\Views\\EventLog\\Edit.cshtml(38,135): error CS1061: 'Result<EventLog>' does not contain a definition for 'HostName' and no extension method 'HostName' accepting a first argument of type 'Result<EventLog>' could be found (are you missing a using directive or an assembly reference?)\r\nD:\\Store\\VisualStudio\\2017\\Project\\SampleCoreArch\\SampleCoreArch.Web\\Views\\EventLog\\Edit.cshtml(39,135): error CS1061: 'Result<EventLog>' does not contain a definition for 'HostName' and no extension method 'HostName' accepting a first argument of type 'Result<EventLog>' could be found (are you missing a using directive or an assembly reference?)\r\nD:\\Store\\VisualStudio\\2017\\Project\\SampleCoreArch\\SampleCoreArch.Web\\Views\\EventLog\\Edit.cshtml(40,147): error CS1061: 'Result<EventLog>' does not contain a definition for 'HostName' and no extension method 'HostName' accepting a first argument of type 'Result<EventLog>' could be found (are you missing a using directive or an assembly reference?)\r\nD:\\Store\\VisualStudio\\2017\\Project\\SampleCoreArch\\SampleCoreArch.Web\\Views\\EventLog\\Edit.cshtml(43,135): error CS1061: 'Result<EventLog>' does not contain a definition for 'CreatedTime' and no extension method 'CreatedTime' accepting a first argument of type 'Result<EventLog>' could be found (are you missing a using directive or an assembly reference?)\r\nD:\\Store\\VisualStudio\\2017\\Project\\SampleCoreArch\\SampleCoreArch.Web\\Views\\EventLog\\Edit.cshtml(44,135): error CS1061: 'Result<EventLog>' does not contain a definition for 'CreatedTime' and no extension method 'CreatedTime' accepting a first argument of type 'Result<EventLog>' could be found (are you missing a using directive or an assembly reference?)\r\nD:\\Store\\VisualStudio\\2017\\Project\\SampleCoreArch\\SampleCoreArch.Web\\Views\\EventLog\\Edit.cshtml(45,147): error CS1061: 'Result<EventLog>' does not contain a definition for 'CreatedTime' and no extension method 'CreatedTime' accepting a first argument of type 'Result<EventLog>' could be found (are you missing a using directive or an assembly reference?)\r\n   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.CompileAndEmit(RazorCodeDocument codeDocument, String generatedCode)\r\n   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.CompileAndEmit(String relativePath)\r\n   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.CreateCacheEntry(String normalizedPath)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRazorPageFactoryProvider.CreateFactory(String relativePath)\r\n   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.CreateCacheResult(HashSet`1 expirationTokens, String relativePath, Boolean isMainPage)\r\n   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.OnCacheMiss(ViewLocationExpanderContext expanderContext, ViewLocationCacheKey cacheKey)\r\n   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.LocatePageFromViewLocations(ActionContext actionContext, String pageName, Boolean isMainPage)\r\n   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)\r\n   at Microsoft.AspNetCore.Mvc.ViewEngines.CompositeViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)\r\n   at Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ViewResultExecutor.FindView(ActionContext actionContext, ViewResult viewResult)\r\n   at Microsoft.AspNetCore.Mvc.ViewResult.<ExecuteResultAsync>d__26.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeResultAsync>d__19.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResultFilterAsync>d__24.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()","EventId":0,"LogLevel":"Error","IpAdress":"192.168.1.107","HostName":"DESKTOP-F285UFK","CreatedTime":"2018-01-20T14:38:08.1693009Z"},
{"Id":102,"Message":"{\"Id\":0,\"Message\":\"mesaj\",\"EventId\":1,\"LogLevel\":\"Info\",\"IpAdress\":\"1\",\"HostName\":\"test\",\"CreatedTime\":\"2018-01-20T17:40:19.4971789+03:00\"}","EventId":0,"LogLevel":"Error","IpAdress":"192.168.1.107","HostName":"DESKTOP-F285UFK","CreatedTime":"2018-01-20T14:40:19.4976241Z"},
{"Id":103,"Message":"{\"Id\":0,\"Message\":\"mesaj\",\"EventId\":1,\"LogLevel\":\"Info\",\"IpAdress\":\"1\",\"HostName\":\"test\",\"CreatedTime\":\"2018-01-20T17:41:44.2166187+03:00\"}","EventId":0,"LogLevel":"Error","IpAdress":"192.168.1.107","HostName":"DESKTOP-F285UFK","CreatedTime":"2018-01-20T14:41:44.2714747Z"},
{"Id":104,"Message":"{\"Id\":0,\"Message\":\"mesaj\",\"EventId\":1,\"LogLevel\":\"Info\",\"IpAdress\":\"1\",\"HostName\":\"test\",\"CreatedTime\":\"2018-01-20T17:42:21.7473998+03:00\"}","EventId":0,"LogLevel":"Error","IpAdress":"192.168.1.107","HostName":"DESKTOP-F285UFK","CreatedTime":"2018-01-20T14:42:21.8011345Z"},
{"Id":105,"Message":"{\"Id\":0,\"Message\":\"mesaj\",\"EventId\":1,\"LogLevel\":\"Info\",\"IpAdress\":\"1\",\"HostName\":\"test\",\"CreatedTime\":\"2018-01-20T17:43:42.340784+03:00\"}","EventId":0,"LogLevel":"Error","IpAdress":"192.168.1.107","HostName":"DESKTOP-F285UFK","CreatedTime":"2018-01-20T14:43:42.3829996Z"},
{"Id":106,"Message":"{\"Id\":0,\"Message\":\"mesaj\",\"EventId\":1,\"LogLevel\":\"Info\",\"IpAdress\":\"1\",\"HostName\":\"test\",\"CreatedTime\":\"2018-01-20T17:43:52.8979113+03:00\"}","EventId":0,"LogLevel":"Error","IpAdress":"192.168.1.107","HostName":"DESKTOP-F285UFK","CreatedTime":"2018-01-20T14:43:52.8983969Z"},
{"Id":107,"Message":"{\"Id\":0,\"Message\":\"mesaj\",\"EventId\":1,\"LogLevel\":\"Info\",\"IpAdress\":\"1\",\"HostName\":\"test\",\"CreatedTime\":\"2018-01-20T17:48:42.3801803+03:00\"}","EventId":0,"LogLevel":"Error","IpAdress":"192.168.1.107","HostName":"DESKTOP-F285UFK","CreatedTime":"2018-01-20T14:48:42.4399616Z"},
{"Id":108,"Message":"{\"Id\":0,\"Message\":\"mesaj\",\"EventId\":1,\"LogLevel\":\"Info\",\"IpAdress\":\"1\",\"HostName\":\"test\",\"CreatedTime\":\"2018-01-20T23:13:12.6810167+03:00\"}","EventId":0,"LogLevel":"Error","IpAdress":"192.168.1.107","HostName":"DESKTOP-F285UFK","CreatedTime":"2018-01-20T20:13:12.7222236Z"},
{"Id":109,"Message":"{\"Id\":0,\"Message\":\"mesaj\",\"EventId\":1,\"LogLevel\":\"Info\",\"IpAdress\":\"1\",\"HostName\":\"test\",\"CreatedTime\":\"2018-01-20T23:13:20.0265586+03:00\"}","EventId":0,"LogLevel":"Error","IpAdress":"192.168.1.107","HostName":"DESKTOP-F285UFK","CreatedTime":"2018-01-20T20:13:20.0269766Z"},
{"Id":110,"Message":"{\"Id\":0,\"Message\":\"mesaj\",\"EventId\":1,\"LogLevel\":\"Info\",\"IpAdress\":\"1\",\"HostName\":\"test\",\"CreatedTime\":\"2018-01-20T23:39:27.0833871+03:00\"}","EventId":0,"LogLevel":"Error","IpAdress":"192.168.1.107","HostName":"DESKTOP-F285UFK","CreatedTime":"2018-01-20T20:39:27.0840326Z"},
